"""Page 2 — chat agent (Ollama) that calls the model through a tool.

The agent logic lives in ``agent.py`` (UI-independent, shared with the Discord
bot). This file is only the Streamlit front-end around it.
"""

import ollama
import streamlit as st

from agent import DEFAULT_MODEL, run_agent


def render_tool_steps(tool_steps):
    for step in tool_steps:
        with st.expander(f"🔧 Tool call: `{step['tool']}`"):
            st.write("**Arguments (generated by the agent)**")
            st.json(step["args"])
            st.write("**Result (from the model)**")
            st.json(step["result"])


st.title("💬 Chat agent")
st.caption(
    "A local LLM agent (via Ollama) answers questions and calls the prediction "
    "model as a **tool** to do so."
)

with st.sidebar:
    st.header("⚙️ Settings")
    try:
        available = [m.model for m in ollama.list().models]
    except Exception:
        available = [DEFAULT_MODEL]
    default_idx = available.index(DEFAULT_MODEL) if DEFAULT_MODEL in available else 0
    model_name = st.selectbox("Ollama model", available, index=default_idx)
    st.caption("The model must support tool calling.")
    if st.button("🗑️ Clear history", use_container_width=True):
        st.session_state.chat = []
        st.rerun()

if "chat" not in st.session_state:
    st.session_state.chat = []

# Replay history.
for msg in st.session_state.chat:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        render_tool_steps(msg.get("tool_steps", []))

# New input.
if prompt := st.chat_input("e.g.: Does a 45-year-old manager working 60 hours/week earn over 50K?"):
    st.session_state.chat.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    history = [{"role": m["role"], "content": m["content"]} for m in st.session_state.chat]
    with st.chat_message("assistant"):
        try:
            with st.spinner("Agent is thinking …"):
                answer, tool_steps = run_agent(history, model_name)
            if not answer.strip():
                answer = "_(The model returned no text answer — see the tool call below.)_"
        except Exception as exc:
            answer, tool_steps = (
                f"⚠️ Connection to Ollama failed: `{exc}`\n\n"
                "Is the Ollama server running (`ollama serve`)? And is the selected "
                "model available (`ollama list`)?",
                [],
            )
        st.markdown(answer)
        render_tool_steps(tool_steps)

    st.session_state.chat.append(
        {"role": "assistant", "content": answer, "tool_steps": tool_steps}
    )
